version: "3.8"

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./reports:/app/reports
    environment:
      - NODE_ENV=test
    command: npm run test:ci
    depends_on:
      - app-dev

  # Report server
  reports:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./reports:/usr/share/nginx/html
    depends_on:
      - test-runner

  # CI/CD simulation
  ci-build:
    build:
      context: .
      dockerfile: Dockerfile.ci
      target: test
    volumes:
      - ./reports:/app/reports
    environment:
      - CI=true
    command: |
      sh -c "
        echo 'Running CI/CD pipeline...'
        npm run test:ci
        echo 'Tests completed. Reports available in ./reports/'
      "
